### ISSUE TITLE
some jars missing

### ISSUE THREAD

**Issue by homelesser** [TeamCohen/SEAL#1]
As the title, when I use the command ant, it seems that there are some jars missing, which should be int the directory "SEAL/lib/". This will cause errors.

**Comment by krivard** [comment]
Should be fixed in c853a26f83231fcd0619d18a59d7a1d66b6131e1

**Comment by homelesser** [comment]
I tried to configure SEAL for online use as the README.md. When I tried to
run (java -Xmx512M -Dfile.encoding=UTF-8 com.rcwang.seal.expand.Seal "Hugo
Chavez" "Fidel Castro"), it got this below.

Exception in thread "main" java.lang.NoClassDefFoundError: Seal (wrong
name: com/rcwang/seal/expand/Seal)
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
Could not find the main class: Seal. Program will exit.

What I should do?

2014-05-14 20:48 GMT+08:00 krivard notifications@github.com:

> Should be fixed in c853a26https://github.com/TeamCohen/SEAL/commit/c853a26f83231fcd0619d18a59d7a1d66b6131e1
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/TeamCohen/SEAL/issues/1#issuecomment-43075522
> .

## 

Jianan Wu (吴佳男)
Harbin Institute of Technology (哈尔滨工业大学)
(+86) 15804509201
homelessers[at]gmail.com
